### ISSUE TITLE
(Testing documentation improvement) Create a repository for compatibility reports

### ISSUE THREAD

**Issue by hardBSDk** [obhq/obliteration#1088]
Most open-source emulators do this, it allows better cooperation and easy website maintenance.

(Also the compatibility list don't load the items on my Firefox)

**Comment by SuchAFuriousDeath** [comment]
https://github.com/obhq/compatibility

**Comment by ultimaweapon** [comment]
Actually I still don't believe we need this. The reason is because:

- We reuse the whole PS4 libraries and services.
- We don't stub things. All implemented code have the same behavior as the PS4 kernel and all unimplemented code path always guarded by `todo` macro.

So it is unlikely we will hit by an unknown behavior. The user should either hit by a panic from `todo` macro or the game working flawlessly. I prefer to have the user report about the panic here instead of a separate repository because it is easier to track what we need to do and it can link a PR to close the issue.

**Comment by hardBSDk** [comment]
@ultimaweapon Can you pin the compatibility list repository on the organization?

**Comment by ultimaweapon** [comment]
Let's wait until we really need it.
