### ISSUE TITLE
New logger prevents GUI usages due to expecting --clear-debug-dump

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#270]
When launching a game via the GUI after the new logger has been added now makes the kernel immediately stop with the error:

```
error: a value is required for '--clear-debug-dump <CLEAR_DEBUG_DUMP>' but none was supplied
  [possible values: true, false]

For more information, try '--help'.
```

**Comment by VocalFan** [comment]
Also, Ultima, me and Jani agree you should get slightly picked on for telling me all the time to check my work... When you didn't even test the GUI when you made the new logger lol.

**Comment by ultimaweapon** [comment]
It is a different story. Your problem is you like to claim that your works is working correctly even when I doubt and when I ask you for the evident it is end up not what you have claimed. It is even get worst because you even confirmed it is working correctly when I asked. That why I don't trust any of your words until I saw the actual evident.

For this issue it is a normal bug in the software development, which should be prevented by automated tests but we don't have that yet.
